### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by arcanedev-maroc** [ARCANEDEV/LaravelApiHelper#1]
* [ ] Adding Laravel Support:
    * [x] Laravel `5.4`
    * [ ] Laravel `5.3`
    * [ ] Laravel `5.2`
    * [ ] Laravel `5.1`
  * [x] Adding data transformer.
  * [x] Adding a custom `json_response` helper & Trait.
